language: python

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "pypy"
  - "pypy3"

install:
  - pip install -U pip
  - pip install -U coverage coveralls flake8
  - pip install -U -r requirements.txt

before_script:
  - flake8 .

script: coverage run --source=word_tools.py test_word_tools.py

after_success:
  - coverage report
  - coveralls

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: "pypy"
    - python: "pypy3"
