language: python

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  fast_finish: true
  include:
    - python: pypy3
    - python: 3.9
    - python: 3.8
    - python: 3.7
    - python: 3.6

install:
  - pip install -U pip
  - pip install -U coverage coveralls flake8
  - pip install -U -r requirements.txt
  - pip install -U black

script:
  # Static analysis
  - flake8 --statistics --count
  - black --check --diff .

  # Unit tests
  - cp example_wordnik_secrets.py wordnik_secrets.py
  - coverage run --source=word_tools.py test_word_tools.py

after_success:
  - coverage report
  - coveralls
