language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - "pypy"

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

install:
  - pip install flake8
  - pip install twitter
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install wordnik-py3; else pip install wordnik; fi

before_script:
  - flake8 .

script: coverage run --source=word_tools.py test_word_tools.py

after_success:
  - coverage report
  - coveralls

matrix:
  allow_failures:
    - python: 2.6
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: "pypy"
