language: python

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  fast_finish: true
  include:
    - python: pypy
    - python: pypy3
    - python: 2.7
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4

install:
  - pip install -U pip
  - pip install -U coverage coveralls flake8
  - pip install -U -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi

script:
  # Static analysis
  - flake8 --statistics --count
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi

  # Unit tests
  - cp example_wordnik_secrets.py wordnik_secrets.py
  - coverage run --source=word_tools.py test_word_tools.py

after_success:
  - coverage report
  - coveralls
